//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("BusDatabaseModel1", "FK_Destination_Bus_BusNo_", "Bus", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BusDatabaseModel1.Bus), "Destination", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BusDatabaseModel1.Destination))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("BusDatabaseModel1", "FK_Passenger_BusNo_BusNo_", "Bus", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BusDatabaseModel1.Bus), "Passenger", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BusDatabaseModel1.Passenger))]

// Original file name:
// Generation date: 22-Feb-17 1:28:09 PM
namespace BusDatabaseModel1
{
    
    /// <summary>
    /// There are no comments for BusDatabaseModel1.Bus in the schema.
    /// </summary>
    /// <KeyProperties>
    /// BusNo
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="BusDatabaseModel1", Name="Bus")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Bus : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Bus object.
        /// </summary>
        /// <param name="busNo">Initial value of BusNo.</param>
        /// <param name="busName">Initial value of BusName.</param>
        /// <param name="time">Initial value of Time.</param>
        /// <param name="seats">Initial value of Seats.</param>
        /// <param name="fare">Initial value of Fare.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Bus CreateBus(int busNo, string busName, global::System.TimeSpan time, int seats, int fare)
        {
            Bus bus = new Bus();
            bus.BusNo = busNo;
            bus.BusName = busName;
            bus.Time = time;
            bus.Seats = seats;
            bus.Fare = fare;
            return bus;
        }
        /// <summary>
        /// There are no comments for property BusNo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int BusNo
        {
            get
            {
                return this._BusNo;
            }
            set
            {
                this.OnBusNoChanging(value);
                this.ReportPropertyChanging("BusNo");
                this._BusNo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("BusNo");
                this.OnBusNoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _BusNo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnBusNoChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnBusNoChanged();
        /// <summary>
        /// There are no comments for property BusName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string BusName
        {
            get
            {
                return this._BusName;
            }
            set
            {
                this.OnBusNameChanging(value);
                this.ReportPropertyChanging("BusName");
                this._BusName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("BusName");
                this.OnBusNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _BusName;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnBusNameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnBusNameChanged();
        /// <summary>
        /// There are no comments for property Time in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.TimeSpan Time
        {
            get
            {
                return this._Time;
            }
            set
            {
                this.OnTimeChanging(value);
                this.ReportPropertyChanging("Time");
                this._Time = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Time");
                this.OnTimeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.TimeSpan _Time;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTimeChanging(global::System.TimeSpan value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTimeChanged();
        /// <summary>
        /// There are no comments for property Seats in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int Seats
        {
            get
            {
                return this._Seats;
            }
            set
            {
                this.OnSeatsChanging(value);
                this.ReportPropertyChanging("Seats");
                this._Seats = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Seats");
                this.OnSeatsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _Seats;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSeatsChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSeatsChanged();
        /// <summary>
        /// There are no comments for property Fare in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int Fare
        {
            get
            {
                return this._Fare;
            }
            set
            {
                this.OnFareChanging(value);
                this.ReportPropertyChanging("Fare");
                this._Fare = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Fare");
                this.OnFareChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _Fare;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFareChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFareChanged();
        /// <summary>
        /// There are no comments for Destinations in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("BusDatabaseModel1", "FK_Destination_Bus_BusNo_", "Destination")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Destination> Destinations
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Destination>("BusDatabaseModel1.FK_Destination_Bus_BusNo_", "Destination");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Destination>("BusDatabaseModel1.FK_Destination_Bus_BusNo_", "Destination", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Passengers in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("BusDatabaseModel1", "FK_Passenger_BusNo_BusNo_", "Passenger")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Passenger> Passengers
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Passenger>("BusDatabaseModel1.FK_Passenger_BusNo_BusNo_", "Passenger");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Passenger>("BusDatabaseModel1.FK_Passenger_BusNo_BusNo_", "Passenger", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for BusDatabaseModel1.Passenger in the schema.
    /// </summary>
    /// <KeyProperties>
    /// BookID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="BusDatabaseModel1", Name="Passenger")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Passenger : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Passenger object.
        /// </summary>
        /// <param name="bookID">Initial value of BookID.</param>
        /// <param name="passName">Initial value of PassName.</param>
        /// <param name="seats">Initial value of Seats.</param>
        /// <param name="dOJ">Initial value of DOJ.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Passenger CreatePassenger(int bookID, string passName, int seats, global::System.DateTime dOJ)
        {
            Passenger passenger = new Passenger();
            passenger.BookID = bookID;
            passenger.PassName = passName;
            passenger.Seats = seats;
            passenger.DOJ = dOJ;
            return passenger;
        }
        /// <summary>
        /// There are no comments for property BookID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int BookID
        {
            get
            {
                return this._BookID;
            }
            set
            {
                this.OnBookIDChanging(value);
                this.ReportPropertyChanging("BookID");
                this._BookID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("BookID");
                this.OnBookIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _BookID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnBookIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnBookIDChanged();
        /// <summary>
        /// There are no comments for property PassName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string PassName
        {
            get
            {
                return this._PassName;
            }
            set
            {
                this.OnPassNameChanging(value);
                this.ReportPropertyChanging("PassName");
                this._PassName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("PassName");
                this.OnPassNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _PassName;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPassNameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPassNameChanged();
        /// <summary>
        /// There are no comments for property Seats in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int Seats
        {
            get
            {
                return this._Seats;
            }
            set
            {
                this.OnSeatsChanging(value);
                this.ReportPropertyChanging("Seats");
                this._Seats = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Seats");
                this.OnSeatsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _Seats;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSeatsChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSeatsChanged();
        /// <summary>
        /// There are no comments for property DOJ in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime DOJ
        {
            get
            {
                return this._DOJ;
            }
            set
            {
                this.OnDOJChanging(value);
                this.ReportPropertyChanging("DOJ");
                this._DOJ = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DOJ");
                this.OnDOJChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _DOJ;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDOJChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDOJChanged();
        /// <summary>
        /// There are no comments for Bus in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("BusDatabaseModel1", "FK_Passenger_BusNo_BusNo_", "Bus")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Bus Bus
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Bus>("BusDatabaseModel1.FK_Passenger_BusNo_BusNo_", "Bus").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Bus>("BusDatabaseModel1.FK_Passenger_BusNo_BusNo_", "Bus").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Bus in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Bus> BusReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Bus>("BusDatabaseModel1.FK_Passenger_BusNo_BusNo_", "Bus");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Bus>("BusDatabaseModel1.FK_Passenger_BusNo_BusNo_", "Bus", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for BusDatabaseModel1.Destination in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Dest
    /// BusNo
    /// Days
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="BusDatabaseModel1", Name="Destination")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Destination : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Destination object.
        /// </summary>
        /// <param name="dest">Initial value of Dest.</param>
        /// <param name="busNo">Initial value of BusNo.</param>
        /// <param name="days">Initial value of Days.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Destination CreateDestination(string dest, int busNo, string days)
        {
            Destination destination = new Destination();
            destination.Dest = dest;
            destination.BusNo = busNo;
            destination.Days = days;
            return destination;
        }
        /// <summary>
        /// There are no comments for property Dest in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Dest
        {
            get
            {
                return this._Dest;
            }
            set
            {
                this.OnDestChanging(value);
                this.ReportPropertyChanging("Dest");
                this._Dest = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Dest");
                this.OnDestChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Dest;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDestChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDestChanged();
        /// <summary>
        /// There are no comments for property BusNo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int BusNo
        {
            get
            {
                return this._BusNo;
            }
            set
            {
                this.OnBusNoChanging(value);
                this.ReportPropertyChanging("BusNo");
                this._BusNo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("BusNo");
                this.OnBusNoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _BusNo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnBusNoChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnBusNoChanged();
        /// <summary>
        /// There are no comments for property Days in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Days
        {
            get
            {
                return this._Days;
            }
            set
            {
                this.OnDaysChanging(value);
                this.ReportPropertyChanging("Days");
                this._Days = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Days");
                this.OnDaysChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Days;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDaysChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDaysChanged();
        /// <summary>
        /// There are no comments for Bus in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("BusDatabaseModel1", "FK_Destination_Bus_BusNo_", "Bus")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Bus Bus
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Bus>("BusDatabaseModel1.FK_Destination_Bus_BusNo_", "Bus").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Bus>("BusDatabaseModel1.FK_Destination_Bus_BusNo_", "Bus").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Bus in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Bus> BusReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Bus>("BusDatabaseModel1.FK_Destination_Bus_BusNo_", "Bus");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Bus>("BusDatabaseModel1.FK_Destination_Bus_BusNo_", "Bus", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for BusDatabaseEntities1 in the schema.
    /// </summary>
    public partial class BusDatabaseEntities1 : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new BusDatabaseEntities1 object using the connection string found in the 'BusDatabaseEntities1' section of the application configuration file.
        /// </summary>
        public BusDatabaseEntities1() : 
                base("name=BusDatabaseEntities1", "BusDatabaseEntities1")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new BusDatabaseEntities1 object.
        /// </summary>
        public BusDatabaseEntities1(string connectionString) : 
                base(connectionString, "BusDatabaseEntities1")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new BusDatabaseEntities1 object.
        /// </summary>
        public BusDatabaseEntities1(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "BusDatabaseEntities1")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Buses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Bus> Buses
        {
            get
            {
                if ((this._Buses == null))
                {
                    this._Buses = base.CreateQuery<Bus>("[Buses]");
                }
                return this._Buses;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Bus> _Buses;
        /// <summary>
        /// There are no comments for Passengers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Passenger> Passengers
        {
            get
            {
                if ((this._Passengers == null))
                {
                    this._Passengers = base.CreateQuery<Passenger>("[Passengers]");
                }
                return this._Passengers;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Passenger> _Passengers;
        /// <summary>
        /// There are no comments for Destinations in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Destination> Destinations
        {
            get
            {
                if ((this._Destinations == null))
                {
                    this._Destinations = base.CreateQuery<Destination>("[Destinations]");
                }
                return this._Destinations;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Destination> _Destinations;
        /// <summary>
        /// There are no comments for Buses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToBuses(Bus bus)
        {
            base.AddObject("Buses", bus);
        }
        /// <summary>
        /// There are no comments for Passengers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToPassengers(Passenger passenger)
        {
            base.AddObject("Passengers", passenger);
        }
        /// <summary>
        /// There are no comments for Destinations in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToDestinations(Destination destination)
        {
            base.AddObject("Destinations", destination);
        }
    }
}
